// <auto-generated />
using GearShop.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GearShop.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190629100703_CorrectedPantTable")]
    partial class CorrectedPantTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.3-servicing-35854")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("GearShop.Models.Helmet", b =>
                {
                    b.Property<int>("HId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("HBrand");

                    b.Property<string>("HColor");

                    b.Property<string>("HImageUrl");

                    b.Property<string>("HModel");

                    b.Property<double>("HPrice");

                    b.Property<int>("HQuantityOnHand");

                    b.Property<double>("HSalePrice");

                    b.Property<string>("HSize");

                    b.Property<bool>("IsHOfTheWeek");

                    b.HasKey("HId");

                    b.ToTable("Helmets");
                });

            modelBuilder.Entity("GearShop.Models.Jersey", b =>
                {
                    b.Property<int>("JId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsJOfTheWeek");

                    b.Property<string>("JBrand");

                    b.Property<string>("JColor");

                    b.Property<string>("JImageUrl");

                    b.Property<string>("JModel");

                    b.Property<double>("JPrice");

                    b.Property<int>("JQuantityOnHand");

                    b.Property<double>("JSalePrice");

                    b.Property<string>("JSize");

                    b.HasKey("JId");

                    b.ToTable("Jerseys");
                });

            modelBuilder.Entity("GearShop.Models.Pant", b =>
                {
                    b.Property<int>("PId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<bool>("IsPOfTheWeek");

                    b.Property<string>("PBrand");

                    b.Property<string>("PColor");

                    b.Property<string>("PImageUrl");

                    b.Property<string>("PModel");

                    b.Property<double>("PPrice");

                    b.Property<int>("PQuantityOnHand");

                    b.Property<double>("PSalePrice");

                    b.Property<int>("PSize");

                    b.HasKey("PId");

                    b.ToTable("Pants");
                });
#pragma warning restore 612, 618
        }
    }
}
